# Form implementation generated from reading ui file 'ui/admin/login.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 640)
        MainWindow.setMinimumSize(QtCore.QSize(920, 560))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget { background-color: #ffffff; }")
        self.centralwidget.setObjectName("centralwidget")
        self.rootLoginLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.rootLoginLayout.setContentsMargins(0, 0, 0, 0)
        self.rootLoginLayout.setSpacing(0)
        self.rootLoginLayout.setObjectName("rootLoginLayout")
        self.leftBranding = QtWidgets.QFrame(parent=self.centralwidget)
        self.leftBranding.setMinimumSize(QtCore.QSize(440, 0))
        self.leftBranding.setStyleSheet("#leftBranding {\n"
"  background-color: transparent;\n"
"  border: none;\n"
"}\n"
"#lblUniNameVi { color: #e2e8f0; font-size: 15px; font-weight: 700; }\n"
"#lblUniNameEn { color: #94a3b8; font-size: 11px; letter-spacing: 1px; }\n"
"#lblBrandBadge {\n"
"  color: #cbd5e1;\n"
"  background-color: rgba(255,255,255,0.08);\n"
"  border: 1px solid rgba(148,163,184,0.35);\n"
"  border-radius: 20px;\n"
"  padding: 6px 14px;\n"
"  font-size: 11px;\n"
"  font-weight: 600;\n"
"}\n"
"#lblBrandTitle { color: #f8fafc; font-size: 26px; font-weight: 700; }\n"
"#lblBrandSub { color: #cbd5e1; font-size: 13px; line-height: 1.5; }\n"
"#lblLogoLeft {\n"
"  background-color: rgba(255,255,255,0.96);\n"
"  border-radius: 14px;\n"
"  border: 1px solid rgba(255,255,255,0.35);\n"
"}")
        self.leftBranding.setObjectName("leftBranding")
        self.leftVBox = QtWidgets.QVBoxLayout(self.leftBranding)
        self.leftVBox.setContentsMargins(40, 48, 36, 40)
        self.leftVBox.setSpacing(18)
        self.leftVBox.setObjectName("leftVBox")
        self.logoTitleRow = QtWidgets.QHBoxLayout()
        self.logoTitleRow.setSpacing(14)
        self.logoTitleRow.setObjectName("logoTitleRow")
        self.lblLogoLeft = QtWidgets.QLabel(parent=self.leftBranding)
        self.lblLogoLeft.setMinimumSize(QtCore.QSize(88, 88))
        self.lblLogoLeft.setMaximumSize(QtCore.QSize(88, 88))
        self.lblLogoLeft.setText("")
        self.lblLogoLeft.setScaledContents(True)
        self.lblLogoLeft.setObjectName("lblLogoLeft")
        self.logoTitleRow.addWidget(self.lblLogoLeft)
        self.uniNamesCol = QtWidgets.QVBoxLayout()
        self.uniNamesCol.setSpacing(2)
        self.uniNamesCol.setObjectName("uniNamesCol")
        self.lblUniNameVi = QtWidgets.QLabel(parent=self.leftBranding)
        self.lblUniNameVi.setObjectName("lblUniNameVi")
        self.uniNamesCol.addWidget(self.lblUniNameVi)
        self.lblUniNameEn = QtWidgets.QLabel(parent=self.leftBranding)
        self.lblUniNameEn.setObjectName("lblUniNameEn")
        self.uniNamesCol.addWidget(self.lblUniNameEn)
        self.logoTitleRow.addLayout(self.uniNamesCol)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.logoTitleRow.addItem(spacerItem)
        self.leftVBox.addLayout(self.logoTitleRow)
        self.lblBrandBadge = QtWidgets.QLabel(parent=self.leftBranding)
        self.lblBrandBadge.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblBrandBadge.setObjectName("lblBrandBadge")
        self.leftVBox.addWidget(self.lblBrandBadge)
        self.lblBrandTitle = QtWidgets.QLabel(parent=self.leftBranding)
        self.lblBrandTitle.setObjectName("lblBrandTitle")
        self.leftVBox.addWidget(self.lblBrandTitle)
        self.lblBrandSub = QtWidgets.QLabel(parent=self.leftBranding)
        self.lblBrandSub.setWordWrap(True)
        self.lblBrandSub.setObjectName("lblBrandSub")
        self.leftVBox.addWidget(self.lblBrandSub)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.leftVBox.addItem(spacerItem1)
        self.rootLoginLayout.addWidget(self.leftBranding)
        self.rightForm = QtWidgets.QFrame(parent=self.centralwidget)
        self.rightForm.setMinimumSize(QtCore.QSize(420, 0))
        self.rightForm.setStyleSheet("#rightForm { background-color: #ffffff; border: none; }\n"
"#lblLoginTitle { font-size: 28px; font-weight: 700; color: #0f172a; }\n"
"#lblLoginSubtitle { font-size: 14px; color: #64748b; }\n"
"#label_4, #label_5 { font-size: 13px; font-weight: 600; color: #334155; }\n"
"#txtTaiKhoan, #txtMatKhau {\n"
"  border: 1px solid #e2e8f0;\n"
"  border-radius: 10px;\n"
"  padding: 10px 14px;\n"
"  font-size: 14px;\n"
"  background: #f8fafc;\n"
"}\n"
"#txtTaiKhoan:focus, #txtMatKhau:focus {\n"
"  border-color: #1d3d71;\n"
"  background: #ffffff;\n"
"}\n"
"#btnDangNhap {\n"
"  background-color: #ffffff;\n"
"  color: #0f172a;\n"
"  border: 2px solid #0f172a;\n"
"  border-radius: 12px;\n"
"  padding: 12px;\n"
"  font-size: 15px;\n"
"  font-weight: 600;\n"
"}\n"
"#btnDangNhap:hover { background-color: #f1f5f9; }\n"
"#label_3 { color: #2563eb; font-size: 13px; }\n"
"#lblTrangThai { font-size: 13px; }")
        self.rightForm.setObjectName("rightForm")
        self.rightVBox = QtWidgets.QVBoxLayout(self.rightForm)
        self.rightVBox.setContentsMargins(48, 56, 56, 48)
        self.rightVBox.setSpacing(14)
        self.rightVBox.setObjectName("rightVBox")
        self.lblLoginTitle = QtWidgets.QLabel(parent=self.rightForm)
        self.lblLoginTitle.setObjectName("lblLoginTitle")
        self.rightVBox.addWidget(self.lblLoginTitle)
        self.lblLoginSubtitle = QtWidgets.QLabel(parent=self.rightForm)
        self.lblLoginSubtitle.setWordWrap(True)
        self.lblLoginSubtitle.setObjectName("lblLoginSubtitle")
        self.rightVBox.addWidget(self.lblLoginSubtitle)
        self.roleRow = QtWidgets.QHBoxLayout()
        self.roleRow.setSpacing(10)
        self.roleRow.setObjectName("roleRow")
        self.btnSinhVien = QtWidgets.QPushButton(parent=self.rightForm)
        self.btnSinhVien.setMinimumSize(QtCore.QSize(0, 40))
        self.btnSinhVien.setObjectName("btnSinhVien")
        self.roleRow.addWidget(self.btnSinhVien)
        self.btnGiangVien = QtWidgets.QPushButton(parent=self.rightForm)
        self.btnGiangVien.setMinimumSize(QtCore.QSize(0, 40))
        self.btnGiangVien.setObjectName("btnGiangVien")
        self.roleRow.addWidget(self.btnGiangVien)
        self.btnQuanTri = QtWidgets.QPushButton(parent=self.rightForm)
        self.btnQuanTri.setMinimumSize(QtCore.QSize(0, 40))
        self.btnQuanTri.setObjectName("btnQuanTri")
        self.roleRow.addWidget(self.btnQuanTri)
        self.rightVBox.addLayout(self.roleRow)
        spacerItem2 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.rightVBox.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(parent=self.rightForm)
        self.label_4.setObjectName("label_4")
        self.rightVBox.addWidget(self.label_4)
        self.txtTaiKhoan = QtWidgets.QLineEdit(parent=self.rightForm)
        self.txtTaiKhoan.setObjectName("txtTaiKhoan")
        self.rightVBox.addWidget(self.txtTaiKhoan)
        self.label_5 = QtWidgets.QLabel(parent=self.rightForm)
        self.label_5.setObjectName("label_5")
        self.rightVBox.addWidget(self.label_5)
        self.passwordRow = QtWidgets.QHBoxLayout()
        self.passwordRow.setSpacing(8)
        self.passwordRow.setObjectName("passwordRow")
        self.txtMatKhau = QtWidgets.QLineEdit(parent=self.rightForm)
        self.txtMatKhau.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtMatKhau.setObjectName("txtMatKhau")
        self.passwordRow.addWidget(self.txtMatKhau)
        self.rightVBox.addLayout(self.passwordRow)
        self.rememberRow = QtWidgets.QHBoxLayout()
        self.rememberRow.setObjectName("rememberRow")
        self.chkGhiNho = QtWidgets.QCheckBox(parent=self.rightForm)
        self.chkGhiNho.setObjectName("chkGhiNho")
        self.rememberRow.addWidget(self.chkGhiNho)
        self.btnToggleMatKhau = QtWidgets.QPushButton(parent=self.rightForm)
        self.btnToggleMatKhau.setMinimumSize(QtCore.QSize(72, 0))
        self.btnToggleMatKhau.setCheckable(True)
        self.btnToggleMatKhau.setObjectName("btnToggleMatKhau")
        self.rememberRow.addWidget(self.btnToggleMatKhau)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.rememberRow.addItem(spacerItem3)
        self.label_3 = QtWidgets.QLabel(parent=self.rightForm)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.rememberRow.addWidget(self.label_3)
        self.rightVBox.addLayout(self.rememberRow)
        self.lblTrangThai = QtWidgets.QLabel(parent=self.rightForm)
        self.lblTrangThai.setText("")
        self.lblTrangThai.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTrangThai.setObjectName("lblTrangThai")
        self.rightVBox.addWidget(self.lblTrangThai)
        self.btnDangNhap = QtWidgets.QPushButton(parent=self.rightForm)
        self.btnDangNhap.setMinimumSize(QtCore.QSize(0, 48))
        self.btnDangNhap.setObjectName("btnDangNhap")
        self.rightVBox.addWidget(self.btnDangNhap)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.rightVBox.addItem(spacerItem4)
        self.rootLoginLayout.addWidget(self.rightForm)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Đăng nhập — Quản lý điểm"))
        self.lblUniNameVi.setText(_translate("MainWindow", "Trường Đại học Công nghệ Đông Á"))
        self.lblUniNameEn.setText(_translate("MainWindow", "EAST ASIA UNIVERSITY OF TECHNOLOGY"))
        self.lblBrandBadge.setText(_translate("MainWindow", "HỆ THỐNG QUẢN LÝ ĐIỂM"))
        self.lblBrandTitle.setText(_translate("MainWindow", "Cổng thông tin\n"
"Đào tạo &\n"
"Quản lý điểm"))
        self.lblBrandSub.setText(_translate("MainWindow", "Nền tảng số hoá cho đào tạo, nhập điểm và quản lý tài khoản người học — giảng viên."))
        self.lblLoginTitle.setText(_translate("MainWindow", "Đăng nhập"))
        self.lblLoginSubtitle.setText(_translate("MainWindow", "Chào mừng trở lại! Vui lòng đăng nhập để tiếp tục."))
        self.btnSinhVien.setText(_translate("MainWindow", "Sinh viên"))
        self.btnGiangVien.setText(_translate("MainWindow", "Giảng viên"))
        self.btnQuanTri.setText(_translate("MainWindow", "Cán bộ"))
        self.label_4.setText(_translate("MainWindow", "Mã số / Tài khoản"))
        self.txtTaiKhoan.setPlaceholderText(_translate("MainWindow", "Nhập MSSV hoặc tên đăng nhập"))
        self.label_5.setText(_translate("MainWindow", "Mật khẩu"))
        self.txtMatKhau.setPlaceholderText(_translate("MainWindow", "Nhập mật khẩu"))
        self.chkGhiNho.setText(_translate("MainWindow", "Ghi nhớ đăng nhập"))
        self.btnToggleMatKhau.setToolTip(_translate("MainWindow", "Hiện / ẩn mật khẩu"))
        self.btnToggleMatKhau.setText(_translate("MainWindow", "Hiện"))
        self.label_3.setText(_translate("MainWindow", "Quên mật khẩu?"))
        self.btnDangNhap.setText(_translate("MainWindow", "Đăng nhập hệ thống"))
