# Form implementation generated from reading ui file 'ui/Sinh viên/sv_dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SVDashboard(object):
    def setupUi(self, SVDashboard):
        SVDashboard.setObjectName("SVDashboard")
        SVDashboard.resize(1280, 859)
        SVDashboard.setStyleSheet("QWidget {\n"
"    background: #f4f7fb;\n"
"    color: #172033;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 13px;\n"
"}\n"
"QLabel {\n"
"    background: transparent;\n"
"}\n"
"QFrame#topBar, QFrame#profileCard, QFrame#passwordCard,\n"
"QFrame#overviewHeaderCard, QFrame#trendCard, QFrame#summaryCard {\n"
"    background: #ffffff;\n"
"    border: 1px solid #dde6ef;\n"
"    border-radius: 8px;\n"
"}\n"
"QFrame#overviewHeaderCard {\n"
"    border-left: 5px solid #0f766e;\n"
"}\n"
"QFrame#statGpa10 {\n"
"    background: #ffffff;\n"
"    border: 1px solid #bde7df;\n"
"    border-left: 5px solid #0f766e;\n"
"    border-radius: 8px;\n"
"}\n"
"QFrame#statGpa4 {\n"
"    background: #ffffff;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-left: 5px solid #2563eb;\n"
"    border-radius: 8px;\n"
"}\n"
"QFrame#statTinChi {\n"
"    background: #ffffff;\n"
"    border: 1px solid #fed7aa;\n"
"    border-left: 5px solid #f59e0b;\n"
"    border-radius: 8px;\n"
"}\n"
"QFrame#statMonRot {\n"
"    background: #ffffff;\n"
"    border: 1px solid #fecdd3;\n"
"    border-left: 5px solid #e11d48;\n"
"    border-radius: 8px;\n"
"}\n"
"QLabel#lblBrand {\n"
"    color: #0f766e;\n"
"    font-size: 20px;\n"
"    font-weight: 800;\n"
"}\n"
"QLabel#lblStudentTitle {\n"
"    color: #475569;\n"
"    font-weight: 600;\n"
"}\n"
"QLabel#lblHeaderName {\n"
"    color: #0f172a;\n"
"    font-size: 24px;\n"
"    font-weight: 800;\n"
"}\n"
"QLabel#lblHeroMetaLine {\n"
"    color: #64748b;\n"
"    font-size: 13px;\n"
"}\n"
"QLabel#lblXepLoaiValue {\n"
"    background: #ecfdf5;\n"
"    color: #047857;\n"
"    border: 1px solid #a7f3d0;\n"
"    border-radius: 14px;\n"
"    padding: 4px 14px;\n"
"    font-size: 13px;\n"
"    font-weight: 700;\n"
"}\n"
"QLabel#lblSectionStats, QLabel#sectionTitle, QLabel#sectionTitle1, QLabel#label13, QLabel#lblHocKy {\n"
"    color: #111827;\n"
"    font-size: 16px;\n"
"    font-weight: 800;\n"
"}\n"
"QLabel#lblKeyGpa10, QLabel#lblKeyGpa4, QLabel#lblKeyTotNghiep, QLabel#lblKeyLegend {\n"
"    color: #64748b;\n"
"    font-size: 12px;\n"
"    font-weight: 700;\n"
"}\n"
"QLabel#mutedLabel, QLabel#lblReadOnly, QLabel#lblPasswordStrength,\n"
"QLabel#lblMonRotCardSub, QLabel#lblTotNghiep {\n"
"    color: #64748b;\n"
"}\n"
"QLabel#lblTrend1, QLabel#lblTrend2, QLabel#lblTrend3, QLabel#lblTrend4, QLabel#lblTrend5 {\n"
"    color: #475569;\n"
"    font-size: 12px;\n"
"    font-weight: 600;\n"
"    min-width: 108px;\n"
"    max-width: 108px;\n"
"}\n"
"QProgressBar#pbTrend1, QProgressBar#pbTrend2, QProgressBar#pbTrend3,\n"
"QProgressBar#pbTrend4, QProgressBar#pbTrend5 {\n"
"    min-height: 26px;\n"
"    max-height: 26px;\n"
"    border: 0;\n"
"    border-radius: 5px;\n"
"    background: #e2e8f0;\n"
"}\n"
"QProgressBar#pbTrend1::chunk, QProgressBar#pbTrend2::chunk, QProgressBar#pbTrend3::chunk,\n"
"QProgressBar#pbTrend4::chunk, QProgressBar#pbTrend5::chunk {\n"
"    background: #0f766e;\n"
"    border-radius: 5px;\n"
"}\n"
"QLabel#lblTrendPct1, QLabel#lblTrendPct2, QLabel#lblTrendPct3,\n"
"QLabel#lblTrendPct4, QLabel#lblTrendPct5 {\n"
"    color: #0f172a;\n"
"    font-size: 11px;\n"
"    font-weight: 700;\n"
"    background: transparent;\n"
"}\n"
"QLabel#label5, QLabel#label6, QLabel#label7, QLabel#label8,\n"
"QLabel#label9, QLabel#label10, QLabel#label11, QLabel#label12 {\n"
"    color: #475569;\n"
"    font-weight: 700;\n"
"}\n"
"QLabel#lblHoTenProfile, QLabel#lblMssvProfile, QLabel#lblLopProfile, QLabel#lblKhoaProfile,\n"
"QLabel#lblNgaySinhProfile, QLabel#lblEmailProfile, QLabel#lblPhoneProfile, QLabel#lblTrangThaiProfile {\n"
"    color: #0f172a;\n"
"    font-weight: 600;\n"
"}\n"
"QLabel#lblGpa10CardBig, QLabel#lblGpa4CardBig, QLabel#lblTinChiCardBig,\n"
"QLabel#lblMonRotCardBig {\n"
"    color: #0f172a;\n"
"    font-size: 30px;\n"
"    font-weight: 800;\n"
"}\n"
"QLabel#lblGpaQuyDoi10, QLabel#lblGpaQuyDoi4, QLabel#lblXepLoaiDuKien {\n"
"    color: #0f172a;\n"
"    font-size: 18px;\n"
"    font-weight: 800;\n"
"}\n"
"QLabel#lblLegend1, QLabel#lblLegend2, QLabel#lblLegend3,\n"
"QLabel#lblLegend4, QLabel#lblLegend5 {\n"
"    color: #475569;\n"
"    font-size: 12px;\n"
"}\n"
"QLabel#lblGpa10Label, QLabel#lblGpa4Label, QLabel#lblTCLabel, QLabel#lblMonRotLabel {\n"
"    color: #64748b;\n"
"    font-size: 12px;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton {\n"
"    background: #ffffff;\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 8px;\n"
"    color: #334155;\n"
"    font-weight: 700;\n"
"    padding: 8px 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #f8fafc;\n"
"    border-color: #94a3b8;\n"
"}\n"
"QPushButton#btnLogout {\n"
"    background: #0f172a;\n"
"    border: 1px solid #0f172a;\n"
"    color: #ffffff;\n"
"}\n"
"QPushButton#btnLogout:hover {\n"
"    background: #1e293b;\n"
"}\n"
"QPushButton#btnChangePassword {\n"
"    background: #0f766e;\n"
"    border-color: #0f766e;\n"
"    color: #ffffff;\n"
"}\n"
"QPushButton#btnChangePassword:hover {\n"
"    background: #115e59;\n"
"}\n"
"QPushButton#btnPillActive, QPushButton#btnTatCa:checked, QPushButton#btnHK202425:checked,\n"
"QPushButton#btnHK202324:checked, QPushButton#btnHK1202324:checked {\n"
"    background: #0f766e;\n"
"    border-color: #0f766e;\n"
"    color: #ffffff;\n"
"}\n"
"QTabWidget::pane {\n"
"    background: #ffffff;\n"
"    border: 1px solid #dde6ef;\n"
"    border-radius: 8px;\n"
"    top: -1px;\n"
"}\n"
"QTabBar::tab {\n"
"    background: #f8fafc;\n"
"    color: #475569;\n"
"    border: 1px solid #e2e8f0;\n"
"    border-radius: 8px;\n"
"    min-width: 118px;\n"
"    min-height: 38px;\n"
"    margin: 0 8px 0 0;\n"
"    padding: 8px 14px;\n"
"    font-weight: 800;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background: #0f766e;\n"
"    color: #ffffff;\n"
"    border-color: #0f766e;\n"
"}\n"
"QLineEdit {\n"
"    background: #ffffff;\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 8px;\n"
"    color: #111827;\n"
"    padding: 9px 12px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #0f766e;\n"
"    padding: 8px 11px;\n"
"}\n"
"QTableWidget {\n"
"    background: #ffffff;\n"
"    alternate-background-color: #f8fafc;\n"
"    border: 1px solid #e2e8f0;\n"
"    border-radius: 8px;\n"
"    gridline-color: #e2e8f0;\n"
"    selection-background-color: #ccfbf1;\n"
"    selection-color: #0f172a;\n"
"}\n"
"QHeaderView::section {\n"
"    background: #f1f5f9;\n"
"    color: #334155;\n"
"    border: 0;\n"
"    border-bottom: 1px solid #e2e8f0;\n"
"    padding: 11px 8px;\n"
"    font-weight: 800;\n"
"}\n"
"QProgressBar#pbPasswordStrength {\n"
"    background: #e2e8f0;\n"
"    border: 0;\n"
"    border-radius: 5px;\n"
"    max-height: 10px;\n"
"}\n"
"QProgressBar#pbPasswordStrength::chunk {\n"
"    background: #0f766e;\n"
"    border-radius: 5px;\n"
"}")
        self.outerLayout = QtWidgets.QVBoxLayout(SVDashboard)
        self.outerLayout.setContentsMargins(24, 20, 24, 20)
        self.outerLayout.setSpacing(16)
        self.outerLayout.setObjectName("outerLayout")
        self.topBar = QtWidgets.QFrame(parent=SVDashboard)
        self.topBar.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.topBar.setObjectName("topBar")
        self.topBarLayout = QtWidgets.QHBoxLayout(self.topBar)
        self.topBarLayout.setContentsMargins(18, 12, 18, 12)
        self.topBarLayout.setObjectName("topBarLayout")
        self.lblBrand = QtWidgets.QLabel(parent=self.topBar)
        self.lblBrand.setObjectName("lblBrand")
        self.topBarLayout.addWidget(self.lblBrand)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.topBarLayout.addItem(spacerItem)
        self.lblStudentTitle = QtWidgets.QLabel(parent=self.topBar)
        self.lblStudentTitle.setObjectName("lblStudentTitle")
        self.topBarLayout.addWidget(self.lblStudentTitle)
        self.btnLogout = QtWidgets.QPushButton(parent=self.topBar)
        self.btnLogout.setMinimumSize(QtCore.QSize(112, 38))
        self.btnLogout.setObjectName("btnLogout")
        self.topBarLayout.addWidget(self.btnLogout)
        self.outerLayout.addWidget(self.topBar)
        self.pages = QtWidgets.QTabWidget(parent=SVDashboard)
        self.pages.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.pages.setDocumentMode(True)
        self.pages.setObjectName("pages")
        self.tabGPA = QtWidgets.QWidget()
        self.tabGPA.setObjectName("tabGPA")
        self.tabGPALayout = QtWidgets.QVBoxLayout(self.tabGPA)
        self.tabGPALayout.setContentsMargins(18, 18, 18, 18)
        self.tabGPALayout.setSpacing(16)
        self.tabGPALayout.setObjectName("tabGPALayout")
        self.overviewHeaderCard = QtWidgets.QFrame(parent=self.tabGPA)
        self.overviewHeaderCard.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.overviewHeaderCard.setObjectName("overviewHeaderCard")
        self.overviewHeaderLayout = QtWidgets.QVBoxLayout(self.overviewHeaderCard)
        self.overviewHeaderLayout.setContentsMargins(22, 18, 22, 18)
        self.overviewHeaderLayout.setSpacing(8)
        self.overviewHeaderLayout.setObjectName("overviewHeaderLayout")
        self.heroTitleRow = QtWidgets.QHBoxLayout()
        self.heroTitleRow.setSpacing(12)
        self.heroTitleRow.setObjectName("heroTitleRow")
        self.lblHeaderName = QtWidgets.QLabel(parent=self.overviewHeaderCard)
        self.lblHeaderName.setObjectName("lblHeaderName")
        self.heroTitleRow.addWidget(self.lblHeaderName)
        self.lblXepLoaiValue = QtWidgets.QLabel(parent=self.overviewHeaderCard)
        self.lblXepLoaiValue.setMinimumSize(QtCore.QSize(0, 28))
        self.lblXepLoaiValue.setMaximumSize(QtCore.QSize(16777215, 28))
        self.lblXepLoaiValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblXepLoaiValue.setWordWrap(False)
        self.lblXepLoaiValue.setObjectName("lblXepLoaiValue")
        self.heroTitleRow.addWidget(self.lblXepLoaiValue)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.heroTitleRow.addItem(spacerItem1)
        self.overviewHeaderLayout.addLayout(self.heroTitleRow)
        self.lblHeroMetaLine = QtWidgets.QLabel(parent=self.overviewHeaderCard)
        self.lblHeroMetaLine.setObjectName("lblHeroMetaLine")
        self.overviewHeaderLayout.addWidget(self.lblHeroMetaLine)
        self.lblHeaderMeta = QtWidgets.QLabel(parent=self.overviewHeaderCard)
        self.lblHeaderMeta.setVisible(False)
        self.lblHeaderMeta.setText("")
        self.lblHeaderMeta.setObjectName("lblHeaderMeta")
        self.overviewHeaderLayout.addWidget(self.lblHeaderMeta)
        self.tabGPALayout.addWidget(self.overviewHeaderCard)
        self.lblSectionStats = QtWidgets.QLabel(parent=self.tabGPA)
        self.lblSectionStats.setObjectName("lblSectionStats")
        self.tabGPALayout.addWidget(self.lblSectionStats)
        self.cardsGPALayout = QtWidgets.QHBoxLayout()
        self.cardsGPALayout.setSpacing(12)
        self.cardsGPALayout.setObjectName("cardsGPALayout")
        self.statGpa10 = QtWidgets.QFrame(parent=self.tabGPA)
        self.statGpa10.setObjectName("statGpa10")
        self.card1Layout = QtWidgets.QVBoxLayout(self.statGpa10)
        self.card1Layout.setContentsMargins(16, 14, 16, 14)
        self.card1Layout.setObjectName("card1Layout")
        self.lblGpa10CardBig = QtWidgets.QLabel(parent=self.statGpa10)
        self.lblGpa10CardBig.setObjectName("lblGpa10CardBig")
        self.card1Layout.addWidget(self.lblGpa10CardBig)
        self.lblGpa10Label = QtWidgets.QLabel(parent=self.statGpa10)
        self.lblGpa10Label.setObjectName("lblGpa10Label")
        self.card1Layout.addWidget(self.lblGpa10Label)
        self.cardsGPALayout.addWidget(self.statGpa10)
        self.statGpa4 = QtWidgets.QFrame(parent=self.tabGPA)
        self.statGpa4.setObjectName("statGpa4")
        self.card2Layout = QtWidgets.QVBoxLayout(self.statGpa4)
        self.card2Layout.setContentsMargins(16, 14, 16, 14)
        self.card2Layout.setObjectName("card2Layout")
        self.lblGpa4CardBig = QtWidgets.QLabel(parent=self.statGpa4)
        self.lblGpa4CardBig.setObjectName("lblGpa4CardBig")
        self.card2Layout.addWidget(self.lblGpa4CardBig)
        self.lblGpa4Label = QtWidgets.QLabel(parent=self.statGpa4)
        self.lblGpa4Label.setObjectName("lblGpa4Label")
        self.card2Layout.addWidget(self.lblGpa4Label)
        self.cardsGPALayout.addWidget(self.statGpa4)
        self.statTinChi = QtWidgets.QFrame(parent=self.tabGPA)
        self.statTinChi.setObjectName("statTinChi")
        self.card3Layout = QtWidgets.QVBoxLayout(self.statTinChi)
        self.card3Layout.setContentsMargins(16, 14, 16, 14)
        self.card3Layout.setObjectName("card3Layout")
        self.lblTinChiCardBig = QtWidgets.QLabel(parent=self.statTinChi)
        self.lblTinChiCardBig.setObjectName("lblTinChiCardBig")
        self.card3Layout.addWidget(self.lblTinChiCardBig)
        self.lblTCLabel = QtWidgets.QLabel(parent=self.statTinChi)
        self.lblTCLabel.setObjectName("lblTCLabel")
        self.card3Layout.addWidget(self.lblTCLabel)
        self.cardsGPALayout.addWidget(self.statTinChi)
        self.statMonRot = QtWidgets.QFrame(parent=self.tabGPA)
        self.statMonRot.setObjectName("statMonRot")
        self.card4Layout = QtWidgets.QVBoxLayout(self.statMonRot)
        self.card4Layout.setContentsMargins(16, 14, 16, 14)
        self.card4Layout.setObjectName("card4Layout")
        self.lblMonRotCardBig = QtWidgets.QLabel(parent=self.statMonRot)
        self.lblMonRotCardBig.setObjectName("lblMonRotCardBig")
        self.card4Layout.addWidget(self.lblMonRotCardBig)
        self.lblMonRotLabel = QtWidgets.QLabel(parent=self.statMonRot)
        self.lblMonRotLabel.setObjectName("lblMonRotLabel")
        self.card4Layout.addWidget(self.lblMonRotLabel)
        self.lblMonRotCardSub = QtWidgets.QLabel(parent=self.statMonRot)
        self.lblMonRotCardSub.setObjectName("lblMonRotCardSub")
        self.card4Layout.addWidget(self.lblMonRotCardSub)
        self.cardsGPALayout.addWidget(self.statMonRot)
        self.tabGPALayout.addLayout(self.cardsGPALayout)
        self.gpaDetailLayout = QtWidgets.QHBoxLayout()
        self.gpaDetailLayout.setSpacing(14)
        self.gpaDetailLayout.setObjectName("gpaDetailLayout")
        self.trendCard = QtWidgets.QFrame(parent=self.tabGPA)
        self.trendCard.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.trendCard.setObjectName("trendCard")
        self.trendLayout = QtWidgets.QVBoxLayout(self.trendCard)
        self.trendLayout.setContentsMargins(18, 16, 18, 16)
        self.trendLayout.setSpacing(10)
        self.trendLayout.setObjectName("trendLayout")
        self.lblHocKy = QtWidgets.QLabel(parent=self.trendCard)
        self.lblHocKy.setObjectName("lblHocKy")
        self.trendLayout.addWidget(self.lblHocKy)
        self.trendRow1Layout = QtWidgets.QHBoxLayout()
        self.trendRow1Layout.setSpacing(12)
        self.trendRow1Layout.setObjectName("trendRow1Layout")
        self.lblTrend1 = QtWidgets.QLabel(parent=self.trendCard)
        self.lblTrend1.setMinimumSize(QtCore.QSize(108, 0))
        self.lblTrend1.setMaximumSize(QtCore.QSize(108, 16777215))
        self.lblTrend1.setObjectName("lblTrend1")
        self.trendRow1Layout.addWidget(self.lblTrend1)
        self.pbTrend1 = QtWidgets.QProgressBar(parent=self.trendCard)
        self.pbTrend1.setMinimumSize(QtCore.QSize(0, 26))
        self.pbTrend1.setMaximum(100)
        self.pbTrend1.setProperty("value", 0)
        self.pbTrend1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pbTrend1.setTextVisible(True)
        self.pbTrend1.setObjectName("pbTrend1")
        self.trendRow1Layout.addWidget(self.pbTrend1)
        self.trendLayout.addLayout(self.trendRow1Layout)
        self.trendRow2Layout = QtWidgets.QHBoxLayout()
        self.trendRow2Layout.setSpacing(12)
        self.trendRow2Layout.setObjectName("trendRow2Layout")
        self.lblTrend2 = QtWidgets.QLabel(parent=self.trendCard)
        self.lblTrend2.setMinimumSize(QtCore.QSize(108, 0))
        self.lblTrend2.setMaximumSize(QtCore.QSize(108, 16777215))
        self.lblTrend2.setObjectName("lblTrend2")
        self.trendRow2Layout.addWidget(self.lblTrend2)
        self.pbTrend2 = QtWidgets.QProgressBar(parent=self.trendCard)
        self.pbTrend2.setMinimumSize(QtCore.QSize(0, 26))
        self.pbTrend2.setMaximum(100)
        self.pbTrend2.setProperty("value", 0)
        self.pbTrend2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pbTrend2.setTextVisible(True)
        self.pbTrend2.setObjectName("pbTrend2")
        self.trendRow2Layout.addWidget(self.pbTrend2)
        self.trendLayout.addLayout(self.trendRow2Layout)
        self.trendRow3Layout = QtWidgets.QHBoxLayout()
        self.trendRow3Layout.setSpacing(12)
        self.trendRow3Layout.setObjectName("trendRow3Layout")
        self.lblTrend3 = QtWidgets.QLabel(parent=self.trendCard)
        self.lblTrend3.setMinimumSize(QtCore.QSize(108, 0))
        self.lblTrend3.setMaximumSize(QtCore.QSize(108, 16777215))
        self.lblTrend3.setObjectName("lblTrend3")
        self.trendRow3Layout.addWidget(self.lblTrend3)
        self.pbTrend3 = QtWidgets.QProgressBar(parent=self.trendCard)
        self.pbTrend3.setMinimumSize(QtCore.QSize(0, 26))
        self.pbTrend3.setMaximum(100)
        self.pbTrend3.setProperty("value", 0)
        self.pbTrend3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pbTrend3.setTextVisible(True)
        self.pbTrend3.setObjectName("pbTrend3")
        self.trendRow3Layout.addWidget(self.pbTrend3)
        self.trendLayout.addLayout(self.trendRow3Layout)
        self.trendRow4Layout = QtWidgets.QHBoxLayout()
        self.trendRow4Layout.setSpacing(12)
        self.trendRow4Layout.setObjectName("trendRow4Layout")
        self.lblTrend4 = QtWidgets.QLabel(parent=self.trendCard)
        self.lblTrend4.setMinimumSize(QtCore.QSize(108, 0))
        self.lblTrend4.setMaximumSize(QtCore.QSize(108, 16777215))
        self.lblTrend4.setObjectName("lblTrend4")
        self.trendRow4Layout.addWidget(self.lblTrend4)
        self.pbTrend4 = QtWidgets.QProgressBar(parent=self.trendCard)
        self.pbTrend4.setMinimumSize(QtCore.QSize(0, 26))
        self.pbTrend4.setMaximum(100)
        self.pbTrend4.setProperty("value", 0)
        self.pbTrend4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pbTrend4.setTextVisible(True)
        self.pbTrend4.setObjectName("pbTrend4")
        self.trendRow4Layout.addWidget(self.pbTrend4)
        self.trendLayout.addLayout(self.trendRow4Layout)
        self.trendRow5Layout = QtWidgets.QHBoxLayout()
        self.trendRow5Layout.setSpacing(12)
        self.trendRow5Layout.setObjectName("trendRow5Layout")
        self.lblTrend5 = QtWidgets.QLabel(parent=self.trendCard)
        self.lblTrend5.setMinimumSize(QtCore.QSize(108, 0))
        self.lblTrend5.setMaximumSize(QtCore.QSize(108, 16777215))
        self.lblTrend5.setObjectName("lblTrend5")
        self.trendRow5Layout.addWidget(self.lblTrend5)
        self.pbTrend5 = QtWidgets.QProgressBar(parent=self.trendCard)
        self.pbTrend5.setMinimumSize(QtCore.QSize(0, 26))
        self.pbTrend5.setMaximum(100)
        self.pbTrend5.setProperty("value", 0)
        self.pbTrend5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pbTrend5.setTextVisible(True)
        self.pbTrend5.setObjectName("pbTrend5")
        self.trendRow5Layout.addWidget(self.pbTrend5)
        self.trendLayout.addLayout(self.trendRow5Layout)
        self.gpaDetailLayout.addWidget(self.trendCard)
        self.summaryCard = QtWidgets.QFrame(parent=self.tabGPA)
        self.summaryCard.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.summaryCard.setObjectName("summaryCard")
        self.summaryLayout = QtWidgets.QVBoxLayout(self.summaryCard)
        self.summaryLayout.setContentsMargins(18, 16, 18, 16)
        self.summaryLayout.setSpacing(10)
        self.summaryLayout.setObjectName("summaryLayout")
        self.sectionTitle = QtWidgets.QLabel(parent=self.summaryCard)
        self.sectionTitle.setObjectName("sectionTitle")
        self.summaryLayout.addWidget(self.sectionTitle)
        self.summaryGrid = QtWidgets.QGridLayout()
        self.summaryGrid.setHorizontalSpacing(12)
        self.summaryGrid.setVerticalSpacing(8)
        self.summaryGrid.setObjectName("summaryGrid")
        self.lblKeyGpa10 = QtWidgets.QLabel(parent=self.summaryCard)
        self.lblKeyGpa10.setObjectName("lblKeyGpa10")
        self.summaryGrid.addWidget(self.lblKeyGpa10, 0, 0, 1, 1)
        self.lblGpaQuyDoi10 = QtWidgets.QLabel(parent=self.summaryCard)
        self.lblGpaQuyDoi10.setObjectName("lblGpaQuyDoi10")
        self.summaryGrid.addWidget(self.lblGpaQuyDoi10, 0, 1, 1, 1)
        self.lblKeyGpa4 = QtWidgets.QLabel(parent=self.summaryCard)
        self.lblKeyGpa4.setObjectName("lblKeyGpa4")
        self.summaryGrid.addWidget(self.lblKeyGpa4, 1, 0, 1, 1)
        self.lblGpaQuyDoi4 = QtWidgets.QLabel(parent=self.summaryCard)
        self.lblGpaQuyDoi4.setObjectName("lblGpaQuyDoi4")
        self.summaryGrid.addWidget(self.lblGpaQuyDoi4, 1, 1, 1, 1)
        self.lblKeyTotNghiep = QtWidgets.QLabel(parent=self.summaryCard)
        self.lblKeyTotNghiep.setObjectName("lblKeyTotNghiep")
        self.summaryGrid.addWidget(self.lblKeyTotNghiep, 2, 0, 1, 1)
        self.lblTotNghiep = QtWidgets.QLabel(parent=self.summaryCard)
        self.lblTotNghiep.setObjectName("lblTotNghiep")
        self.summaryGrid.addWidget(self.lblTotNghiep, 2, 1, 1, 1)
        self.summaryLayout.addLayout(self.summaryGrid)
        self.lblKeyLegend = QtWidgets.QLabel(parent=self.summaryCard)
        self.lblKeyLegend.setObjectName("lblKeyLegend")
        self.summaryLayout.addWidget(self.lblKeyLegend)
        self.lblLegend1 = QtWidgets.QLabel(parent=self.summaryCard)
        self.lblLegend1.setObjectName("lblLegend1")
        self.summaryLayout.addWidget(self.lblLegend1)
        self.lblLegend2 = QtWidgets.QLabel(parent=self.summaryCard)
        self.lblLegend2.setObjectName("lblLegend2")
        self.summaryLayout.addWidget(self.lblLegend2)
        self.lblLegend3 = QtWidgets.QLabel(parent=self.summaryCard)
        self.lblLegend3.setObjectName("lblLegend3")
        self.summaryLayout.addWidget(self.lblLegend3)
        self.lblLegend4 = QtWidgets.QLabel(parent=self.summaryCard)
        self.lblLegend4.setObjectName("lblLegend4")
        self.summaryLayout.addWidget(self.lblLegend4)
        self.lblLegend5 = QtWidgets.QLabel(parent=self.summaryCard)
        self.lblLegend5.setObjectName("lblLegend5")
        self.summaryLayout.addWidget(self.lblLegend5)
        self.lblXepLoaiDuKien = QtWidgets.QLabel(parent=self.summaryCard)
        self.lblXepLoaiDuKien.setVisible(False)
        self.lblXepLoaiDuKien.setText("")
        self.lblXepLoaiDuKien.setObjectName("lblXepLoaiDuKien")
        self.summaryLayout.addWidget(self.lblXepLoaiDuKien)
        self.gpaDetailLayout.addWidget(self.summaryCard)
        self.tabGPALayout.addLayout(self.gpaDetailLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.tabGPALayout.addItem(spacerItem2)
        self.pages.addTab(self.tabGPA, "")
        self.tabBangDiem = QtWidgets.QWidget()
        self.tabBangDiem.setObjectName("tabBangDiem")
        self.tabBangDiemLayout = QtWidgets.QVBoxLayout(self.tabBangDiem)
        self.tabBangDiemLayout.setContentsMargins(18, 18, 18, 18)
        self.tabBangDiemLayout.setSpacing(14)
        self.tabBangDiemLayout.setObjectName("tabBangDiemLayout")
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setSpacing(8)
        self.filterLayout.setObjectName("filterLayout")
        self.label3 = QtWidgets.QLabel(parent=self.tabBangDiem)
        self.label3.setMinimumSize(QtCore.QSize(74, 0))
        self.label3.setObjectName("label3")
        self.filterLayout.addWidget(self.label3)
        self.btnTatCa = QtWidgets.QPushButton(parent=self.tabBangDiem)
        self.btnTatCa.setMinimumSize(QtCore.QSize(86, 36))
        self.btnTatCa.setCheckable(True)
        self.btnTatCa.setChecked(True)
        self.btnTatCa.setObjectName("btnTatCa")
        self.filterLayout.addWidget(self.btnTatCa)
        self.btnHK202425 = QtWidgets.QPushButton(parent=self.tabBangDiem)
        self.btnHK202425.setMinimumSize(QtCore.QSize(118, 36))
        self.btnHK202425.setCheckable(True)
        self.btnHK202425.setObjectName("btnHK202425")
        self.filterLayout.addWidget(self.btnHK202425)
        self.btnHK202324 = QtWidgets.QPushButton(parent=self.tabBangDiem)
        self.btnHK202324.setMinimumSize(QtCore.QSize(118, 36))
        self.btnHK202324.setCheckable(True)
        self.btnHK202324.setObjectName("btnHK202324")
        self.filterLayout.addWidget(self.btnHK202324)
        self.btnHK1202324 = QtWidgets.QPushButton(parent=self.tabBangDiem)
        self.btnHK1202324.setMinimumSize(QtCore.QSize(118, 36))
        self.btnHK1202324.setCheckable(True)
        self.btnHK1202324.setObjectName("btnHK1202324")
        self.filterLayout.addWidget(self.btnHK1202324)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.filterLayout.addItem(spacerItem3)
        self.tabBangDiemLayout.addLayout(self.filterLayout)
        self.tbBangDiem = QtWidgets.QTableWidget(parent=self.tabBangDiem)
        self.tbBangDiem.setAlternatingRowColors(True)
        self.tbBangDiem.setObjectName("tbBangDiem")
        self.tbBangDiem.setColumnCount(7)
        self.tbBangDiem.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbBangDiem.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbBangDiem.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbBangDiem.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbBangDiem.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbBangDiem.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbBangDiem.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbBangDiem.setHorizontalHeaderItem(6, item)
        self.tabBangDiemLayout.addWidget(self.tbBangDiem)
        self.lblReadOnly = QtWidgets.QLabel(parent=self.tabBangDiem)
        self.lblReadOnly.setObjectName("lblReadOnly")
        self.tabBangDiemLayout.addWidget(self.lblReadOnly)
        self.pages.addTab(self.tabBangDiem, "")
        self.tabTraCuu = QtWidgets.QWidget()
        self.tabTraCuu.setObjectName("tabTraCuu")
        self.tabTraCuuLayout = QtWidgets.QVBoxLayout(self.tabTraCuu)
        self.tabTraCuuLayout.setContentsMargins(18, 18, 18, 18)
        self.tabTraCuuLayout.setSpacing(14)
        self.tabTraCuuLayout.setObjectName("tabTraCuuLayout")
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setObjectName("searchLayout")
        self.label4 = QtWidgets.QLabel(parent=self.tabTraCuu)
        self.label4.setMinimumSize(QtCore.QSize(74, 0))
        self.label4.setObjectName("label4")
        self.searchLayout.addWidget(self.label4)
        self.leTraCuuSearch = QtWidgets.QLineEdit(parent=self.tabTraCuu)
        self.leTraCuuSearch.setMinimumSize(QtCore.QSize(300, 38))
        self.leTraCuuSearch.setObjectName("leTraCuuSearch")
        self.searchLayout.addWidget(self.leTraCuuSearch)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.searchLayout.addItem(spacerItem4)
        self.tabTraCuuLayout.addLayout(self.searchLayout)
        self.tbTraCuu = QtWidgets.QTableWidget(parent=self.tabTraCuu)
        self.tbTraCuu.setAlternatingRowColors(True)
        self.tbTraCuu.setObjectName("tbTraCuu")
        self.tbTraCuu.setColumnCount(3)
        self.tbTraCuu.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbTraCuu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbTraCuu.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbTraCuu.setHorizontalHeaderItem(2, item)
        self.tabTraCuuLayout.addWidget(self.tbTraCuu)
        self.pages.addTab(self.tabTraCuu, "")
        self.tabHoSo = QtWidgets.QWidget()
        self.tabHoSo.setObjectName("tabHoSo")
        self.tabHoSoLayout = QtWidgets.QHBoxLayout(self.tabHoSo)
        self.tabHoSoLayout.setContentsMargins(18, 18, 18, 18)
        self.tabHoSoLayout.setSpacing(16)
        self.tabHoSoLayout.setObjectName("tabHoSoLayout")
        self.profileCard = QtWidgets.QFrame(parent=self.tabHoSo)
        self.profileCard.setObjectName("profileCard")
        self.profileLayout = QtWidgets.QGridLayout(self.profileCard)
        self.profileLayout.setContentsMargins(18, 18, 18, 18)
        self.profileLayout.setHorizontalSpacing(18)
        self.profileLayout.setVerticalSpacing(12)
        self.profileLayout.setObjectName("profileLayout")
        self.sectionTitle1 = QtWidgets.QLabel(parent=self.profileCard)
        self.sectionTitle1.setObjectName("sectionTitle1")
        self.profileLayout.addWidget(self.sectionTitle1, 0, 0, 1, 4)
        self.label5 = QtWidgets.QLabel(parent=self.profileCard)
        self.label5.setMinimumSize(QtCore.QSize(110, 0))
        self.label5.setObjectName("label5")
        self.profileLayout.addWidget(self.label5, 1, 0, 1, 1)
        self.lblHoTenProfile = QtWidgets.QLabel(parent=self.profileCard)
        self.lblHoTenProfile.setObjectName("lblHoTenProfile")
        self.profileLayout.addWidget(self.lblHoTenProfile, 1, 1, 1, 1)
        self.label10 = QtWidgets.QLabel(parent=self.profileCard)
        self.label10.setMinimumSize(QtCore.QSize(110, 0))
        self.label10.setObjectName("label10")
        self.profileLayout.addWidget(self.label10, 1, 2, 1, 1)
        self.lblNgaySinhProfile = QtWidgets.QLabel(parent=self.profileCard)
        self.lblNgaySinhProfile.setObjectName("lblNgaySinhProfile")
        self.profileLayout.addWidget(self.lblNgaySinhProfile, 1, 3, 1, 1)
        self.label6 = QtWidgets.QLabel(parent=self.profileCard)
        self.label6.setMinimumSize(QtCore.QSize(110, 0))
        self.label6.setObjectName("label6")
        self.profileLayout.addWidget(self.label6, 2, 0, 1, 1)
        self.lblMssvProfile = QtWidgets.QLabel(parent=self.profileCard)
        self.lblMssvProfile.setObjectName("lblMssvProfile")
        self.profileLayout.addWidget(self.lblMssvProfile, 2, 1, 1, 1)
        self.label12 = QtWidgets.QLabel(parent=self.profileCard)
        self.label12.setMinimumSize(QtCore.QSize(110, 0))
        self.label12.setObjectName("label12")
        self.profileLayout.addWidget(self.label12, 2, 2, 1, 1)
        self.lblTrangThaiProfile = QtWidgets.QLabel(parent=self.profileCard)
        self.lblTrangThaiProfile.setObjectName("lblTrangThaiProfile")
        self.profileLayout.addWidget(self.lblTrangThaiProfile, 2, 3, 1, 1)
        self.label7 = QtWidgets.QLabel(parent=self.profileCard)
        self.label7.setMinimumSize(QtCore.QSize(110, 0))
        self.label7.setObjectName("label7")
        self.profileLayout.addWidget(self.label7, 3, 0, 1, 1)
        self.lblLopProfile = QtWidgets.QLabel(parent=self.profileCard)
        self.lblLopProfile.setObjectName("lblLopProfile")
        self.profileLayout.addWidget(self.lblLopProfile, 3, 1, 1, 1)
        self.label11 = QtWidgets.QLabel(parent=self.profileCard)
        self.label11.setMinimumSize(QtCore.QSize(110, 0))
        self.label11.setObjectName("label11")
        self.profileLayout.addWidget(self.label11, 3, 2, 1, 1)
        self.lblEmailProfile = QtWidgets.QLabel(parent=self.profileCard)
        self.lblEmailProfile.setObjectName("lblEmailProfile")
        self.profileLayout.addWidget(self.lblEmailProfile, 3, 3, 1, 1)
        self.label8 = QtWidgets.QLabel(parent=self.profileCard)
        self.label8.setMinimumSize(QtCore.QSize(110, 0))
        self.label8.setObjectName("label8")
        self.profileLayout.addWidget(self.label8, 4, 0, 1, 1)
        self.lblKhoaProfile = QtWidgets.QLabel(parent=self.profileCard)
        self.lblKhoaProfile.setObjectName("lblKhoaProfile")
        self.profileLayout.addWidget(self.lblKhoaProfile, 4, 1, 1, 1)
        self.label9 = QtWidgets.QLabel(parent=self.profileCard)
        self.label9.setMinimumSize(QtCore.QSize(110, 0))
        self.label9.setObjectName("label9")
        self.profileLayout.addWidget(self.label9, 4, 2, 1, 1)
        self.lblPhoneProfile = QtWidgets.QLabel(parent=self.profileCard)
        self.lblPhoneProfile.setObjectName("lblPhoneProfile")
        self.profileLayout.addWidget(self.lblPhoneProfile, 4, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.profileLayout.addItem(spacerItem5, 5, 0, 1, 4)
        self.tabHoSoLayout.addWidget(self.profileCard)
        self.passwordCard = QtWidgets.QFrame(parent=self.tabHoSo)
        self.passwordCard.setObjectName("passwordCard")
        self.changePasswordLayout = QtWidgets.QGridLayout(self.passwordCard)
        self.changePasswordLayout.setContentsMargins(18, 18, 18, 18)
        self.changePasswordLayout.setSpacing(10)
        self.changePasswordLayout.setObjectName("changePasswordLayout")
        self.label13 = QtWidgets.QLabel(parent=self.passwordCard)
        self.label13.setObjectName("label13")
        self.changePasswordLayout.addWidget(self.label13, 0, 0, 1, 2)
        self.label14 = QtWidgets.QLabel(parent=self.passwordCard)
        self.label14.setMinimumSize(QtCore.QSize(150, 0))
        self.label14.setObjectName("label14")
        self.changePasswordLayout.addWidget(self.label14, 1, 0, 1, 1)
        self.leCurrentPassword = QtWidgets.QLineEdit(parent=self.passwordCard)
        self.leCurrentPassword.setMinimumSize(QtCore.QSize(280, 38))
        self.leCurrentPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.leCurrentPassword.setObjectName("leCurrentPassword")
        self.changePasswordLayout.addWidget(self.leCurrentPassword, 1, 1, 1, 1)
        self.label15 = QtWidgets.QLabel(parent=self.passwordCard)
        self.label15.setObjectName("label15")
        self.changePasswordLayout.addWidget(self.label15, 2, 0, 1, 1)
        self.leNewPassword = QtWidgets.QLineEdit(parent=self.passwordCard)
        self.leNewPassword.setMinimumSize(QtCore.QSize(280, 38))
        self.leNewPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.leNewPassword.setObjectName("leNewPassword")
        self.changePasswordLayout.addWidget(self.leNewPassword, 2, 1, 1, 1)
        self.label16 = QtWidgets.QLabel(parent=self.passwordCard)
        self.label16.setObjectName("label16")
        self.changePasswordLayout.addWidget(self.label16, 3, 0, 1, 1)
        self.leConfirmPassword = QtWidgets.QLineEdit(parent=self.passwordCard)
        self.leConfirmPassword.setMinimumSize(QtCore.QSize(280, 38))
        self.leConfirmPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.leConfirmPassword.setObjectName("leConfirmPassword")
        self.changePasswordLayout.addWidget(self.leConfirmPassword, 3, 1, 1, 1)
        self.pbPasswordStrength = QtWidgets.QProgressBar(parent=self.passwordCard)
        self.pbPasswordStrength.setMaximum(4)
        self.pbPasswordStrength.setProperty("value", 0)
        self.pbPasswordStrength.setTextVisible(False)
        self.pbPasswordStrength.setObjectName("pbPasswordStrength")
        self.changePasswordLayout.addWidget(self.pbPasswordStrength, 4, 1, 1, 1)
        self.lblPasswordStrength = QtWidgets.QLabel(parent=self.passwordCard)
        self.lblPasswordStrength.setObjectName("lblPasswordStrength")
        self.changePasswordLayout.addWidget(self.lblPasswordStrength, 5, 1, 1, 1)
        self.btnChangePassword = QtWidgets.QPushButton(parent=self.passwordCard)
        self.btnChangePassword.setMinimumSize(QtCore.QSize(178, 40))
        self.btnChangePassword.setObjectName("btnChangePassword")
        self.changePasswordLayout.addWidget(self.btnChangePassword, 6, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.changePasswordLayout.addItem(spacerItem6, 7, 0, 1, 2)
        self.tabHoSoLayout.addWidget(self.passwordCard)
        self.pages.addTab(self.tabHoSo, "")
        self.outerLayout.addWidget(self.pages)

        self.retranslateUi(SVDashboard)
        QtCore.QMetaObject.connectSlotsByName(SVDashboard)

    def retranslateUi(self, SVDashboard):
        _translate = QtCore.QCoreApplication.translate
        SVDashboard.setWindowTitle(_translate("SVDashboard", "Quản lý điểm - Sinh viên"))
        self.lblBrand.setText(_translate("SVDashboard", "Cổng sinh viên"))
        self.lblStudentTitle.setText(_translate("SVDashboard", "Nguyễn Văn A (SV001)"))
        self.btnLogout.setText(_translate("SVDashboard", "Đăng xuất"))
        self.lblHeaderName.setText(_translate("SVDashboard", "Nguyễn Văn A"))
        self.lblXepLoaiValue.setText(_translate("SVDashboard", "Giỏi"))
        self.lblHeroMetaLine.setText(_translate("SVDashboard", "SV001 · CNTT01 · Công nghệ thông tin"))
        self.lblSectionStats.setText(_translate("SVDashboard", "Chỉ số học tập"))
        self.lblGpa10CardBig.setText(_translate("SVDashboard", "9.00"))
        self.lblGpa10Label.setText(_translate("SVDashboard", "GPA thang 10"))
        self.lblGpa4CardBig.setText(_translate("SVDashboard", "3.60"))
        self.lblGpa4Label.setText(_translate("SVDashboard", "GPA thang 4"))
        self.lblTinChiCardBig.setText(_translate("SVDashboard", "60"))
        self.lblTCLabel.setText(_translate("SVDashboard", "Tín chỉ đạt"))
        self.lblMonRotCardBig.setText(_translate("SVDashboard", "0"))
        self.lblMonRotLabel.setText(_translate("SVDashboard", "Môn chưa đạt"))
        self.lblMonRotCardSub.setText(_translate("SVDashboard", "-"))
        self.lblHocKy.setText(_translate("SVDashboard", "Xu hướng GPA"))
        self.lblTrend1.setText(_translate("SVDashboard", "HK1 2022-23"))
        self.pbTrend1.setFormat(_translate("SVDashboard", "%p%"))
        self.lblTrend2.setText(_translate("SVDashboard", "HK2 2022-23"))
        self.pbTrend2.setFormat(_translate("SVDashboard", "%p%"))
        self.lblTrend3.setText(_translate("SVDashboard", "HK1 2023-24"))
        self.pbTrend3.setFormat(_translate("SVDashboard", "%p%"))
        self.lblTrend4.setText(_translate("SVDashboard", "HK2 2023-24"))
        self.pbTrend4.setFormat(_translate("SVDashboard", "%p%"))
        self.lblTrend5.setText(_translate("SVDashboard", "HK1 2024-25"))
        self.pbTrend5.setFormat(_translate("SVDashboard", "%p%"))
        self.sectionTitle.setText(_translate("SVDashboard", "Tóm tắt & thang điểm"))
        self.lblKeyGpa10.setText(_translate("SVDashboard", "GPA thang 10"))
        self.lblGpaQuyDoi10.setText(_translate("SVDashboard", "8.24"))
        self.lblKeyGpa4.setText(_translate("SVDashboard", "GPA thang 4"))
        self.lblGpaQuyDoi4.setText(_translate("SVDashboard", "3.30"))
        self.lblKeyTotNghiep.setText(_translate("SVDashboard", "Tốt nghiệp"))
        self.lblTotNghiep.setText(_translate("SVDashboard", "Đủ điều kiện"))
        self.lblKeyLegend.setText(_translate("SVDashboard", "Thang xếp loại (GPA 10)"))
        self.lblLegend1.setText(_translate("SVDashboard", "Xuất sắc"))
        self.lblLegend2.setText(_translate("SVDashboard", "Giỏi"))
        self.lblLegend3.setText(_translate("SVDashboard", "Khá"))
        self.lblLegend4.setText(_translate("SVDashboard", "Trung bình"))
        self.lblLegend5.setText(_translate("SVDashboard", "Yếu / Kém"))
        self.pages.setTabText(self.pages.indexOf(self.tabGPA), _translate("SVDashboard", "Tổng quan"))
        self.label3.setText(_translate("SVDashboard", "Học kỳ"))
        self.btnTatCa.setText(_translate("SVDashboard", "Tất cả"))
        self.btnHK202425.setText(_translate("SVDashboard", "HK1 2024-25"))
        self.btnHK202324.setText(_translate("SVDashboard", "HK2 2023-24"))
        self.btnHK1202324.setText(_translate("SVDashboard", "HK1 2023-24"))
        item = self.tbBangDiem.horizontalHeaderItem(0)
        item.setText(_translate("SVDashboard", "Môn học"))
        item = self.tbBangDiem.horizontalHeaderItem(1)
        item.setText(_translate("SVDashboard", "TC"))
        item = self.tbBangDiem.horizontalHeaderItem(2)
        item.setText(_translate("SVDashboard", "CC"))
        item = self.tbBangDiem.horizontalHeaderItem(3)
        item.setText(_translate("SVDashboard", "GK"))
        item = self.tbBangDiem.horizontalHeaderItem(4)
        item.setText(_translate("SVDashboard", "CK"))
        item = self.tbBangDiem.horizontalHeaderItem(5)
        item.setText(_translate("SVDashboard", "ĐTB"))
        item = self.tbBangDiem.horizontalHeaderItem(6)
        item.setText(_translate("SVDashboard", "Kết quả"))
        self.lblReadOnly.setText(_translate("SVDashboard", "Chỉ hiển thị điểm đã được giảng viên công bố."))
        self.pages.setTabText(self.pages.indexOf(self.tabBangDiem), _translate("SVDashboard", "Bảng điểm"))
        self.label4.setText(_translate("SVDashboard", "Tìm kiếm"))
        self.leTraCuuSearch.setPlaceholderText(_translate("SVDashboard", "Nhập tên môn học..."))
        item = self.tbTraCuu.horizontalHeaderItem(0)
        item.setText(_translate("SVDashboard", "Môn học"))
        item = self.tbTraCuu.horizontalHeaderItem(1)
        item.setText(_translate("SVDashboard", "ĐTB"))
        item = self.tbTraCuu.horizontalHeaderItem(2)
        item.setText(_translate("SVDashboard", "Kết quả"))
        self.pages.setTabText(self.pages.indexOf(self.tabTraCuu), _translate("SVDashboard", "Tra cứu"))
        self.sectionTitle1.setText(_translate("SVDashboard", "Thông tin sinh viên"))
        self.label5.setText(_translate("SVDashboard", "Họ tên"))
        self.lblHoTenProfile.setText(_translate("SVDashboard", "Nguyễn Văn A"))
        self.label10.setText(_translate("SVDashboard", "Ngày sinh"))
        self.lblNgaySinhProfile.setText(_translate("SVDashboard", "-"))
        self.label6.setText(_translate("SVDashboard", "MSSV"))
        self.lblMssvProfile.setText(_translate("SVDashboard", "SV001"))
        self.label12.setText(_translate("SVDashboard", "Trạng thái"))
        self.lblTrangThaiProfile.setText(_translate("SVDashboard", "Đang học"))
        self.label7.setText(_translate("SVDashboard", "Lớp"))
        self.lblLopProfile.setText(_translate("SVDashboard", "CNTT01"))
        self.label11.setText(_translate("SVDashboard", "Email"))
        self.lblEmailProfile.setText(_translate("SVDashboard", "sv001@abc.edu.vn"))
        self.label8.setText(_translate("SVDashboard", "Khoa"))
        self.lblKhoaProfile.setText(_translate("SVDashboard", "CNTT"))
        self.label9.setText(_translate("SVDashboard", "Điện thoại"))
        self.lblPhoneProfile.setText(_translate("SVDashboard", "-"))
        self.label13.setText(_translate("SVDashboard", "Đổi mật khẩu"))
        self.label14.setText(_translate("SVDashboard", "Mật khẩu hiện tại"))
        self.label15.setText(_translate("SVDashboard", "Mật khẩu mới"))
        self.label16.setText(_translate("SVDashboard", "Xác nhận mật khẩu"))
        self.lblPasswordStrength.setText(_translate("SVDashboard", "Độ mạnh: -"))
        self.btnChangePassword.setText(_translate("SVDashboard", "Cập nhật mật khẩu"))
        self.pages.setTabText(self.pages.indexOf(self.tabHoSo), _translate("SVDashboard", "Hồ sơ"))
